spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  application:
    name: cloud-iaas-service
  main:
    allow-bean-definition-overriding: true

server:
  max-http-header-size: 1024000
