spring:
  application:
    name: cloud-platform-service
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
seata:
  application-id: ${spring.application.name}
  tx-service-group: txt_seata_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: 139.9.234.187:8848
  registry:
    type: nacos
    nacos:
      server-addr: 139.9.234.187:8848