package com.hirisun.cloud.model.ncov.contains;

public interface NcovKey {

    String HOME_PAGE = "HOMEPAGE:";
    String HOME_PAGE_IAAS_NCOV_OVERVIEW = "HOMEPAGE:IAAS:NCOVOVERVIEW:";
    String HOME_PAGE_IAAS_NCOV_DESKTOP = "HOMEPAGE:IAAS:DESKTOP:";
    
    String HOME_PAGE_DAAS_DATA_MODELING = "HOMEPAGE:DAAS:DATAMODELING:";
    String HOME_PAGE_DAAS_DATA_MODELING_SETNX = "HOMEPAGE:DAAS:DATAMODELING:SETNX:";
    String HOME_PAGE_DAAS_DATA_SHARING = "HOMEPAGE:DAAS:DATASHARING:";
    String HOME_PAGE_DAAS_DATA_SHARING_SETNX = "HOMEPAGE:DAAS:DATASHARING:SETNX:";
    String HOME_PAGE_DAAS_DATA_SERVICE_COUNT = "HOMEPAGE:DAAS:DATASERVICE:COUNT:";
    String HOME_PAGE_DAAS_DATA_ACCESS = "HOMEPAGE:DAAS:DATAACCESS:";
    String HOME_PAGE_DAAS_DATA_GOVERNANCE = "HOMEPAGE:DAAS:DATAGOVERNANCE:";

    String HOME_PAGE_NCOV_REALTIME = "HOMEPAGE:NCOVREALTIME:";
    
    String HOME_PAGE_PAAS_OVERVIEW = "HOMEPAGE:PAAS:OVERVIEW:";
    String HOME_PAGE_PAAS_RESOURCE = "HOMEPAGE:PAAS:RESOURCE:";
    String HOME_PAGE_PAAS_APPDETAIL = "HOMEPAGE:PAAS:APPDETAIL:";
}
